     <meta charset="utf-8">
     <!-- Online jQuery
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script> -->
     <!-- Loading jQuery --> 
     <script type="text/javascript" src="../js/jquery.min.js"></script>

     <!-- Loading Bootstrap-Select --> 
     <link rel="stylesheet" type="text/css" href="../bootstrap/css/bootstrap-select.css">
     
     <!-- Loading Bootstrap 3.0 --> 
     <link href="../bootstrap/css/bootstrap.css" rel="stylesheet">   

     <!-- Custom styles for this template -->
     <link href="../css/dashboard.css" rel="stylesheet">

     <!-- Loading Flat UI -->
     <link href="../css/flat-ui.css" rel="stylesheet">
     <link rel="shortcut icon" href="../images/favicon.ico">

     <!-- Just for debugging purposes. Don't actually copy this line! -->
     <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

     <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
     <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
     <![endif]-->

      <script type="text/javascript">
          $(window).on('load', function () {

              $('.selectpicker').selectpicker({
                  'selectedText': 'cat'
              });

              // $('.selectpicker').selectpicker('hide');
          });
    </script>